env:
  PACKAGE_NAME: MelonLoader
  PACKAGE_DESC: The World's First Universal Mod Loader for Unity Games compatible with both Il2Cpp and Mono
  PACKAGE_REPO: https://github.com/${{ github.repository }}

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
  
jobs:
  compile_thunderstore:
    name: Create Thunderstore Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        
      - name: Download Windows x64 Artifact
        uses: actions/download-artifact@v6
        with:
          name: MelonLoader.Windows.x64.CI.Release
          path: ./compiled_release/thunderstore
          
      - name: Copy Missing Files
        run: |
          cp icon.png compiled_release/thunderstore/icon.png
          cp compiled_release/thunderstore/MelonLoader/Documentation/README.md compiled_release/thunderstore/README.md
          
      - name: Generate manifest.json
        run: |
          cat <<EOF > compiled_release/thunderstore/manifest.json
          {
              "name": "${{ env.PACKAGE_NAME }}",
              "version_number": "${{ inputs.VERSION }}",
              "website_url": "${{ env.PACKAGE_REPO }}",
              "description": "${{ env.PACKAGE_DESC }}",
              "dependencies": []
          }
          EOF
          
      - name: Package Zip Archive
        run: |
          cd compiled_release/thunderstore
          zip -r ../${{ github.repository_owner }}-${{ env.PACKAGE_NAME }}-${{ inputs.VERSION }}.zip ./

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v5
        with:
          name: MelonLoader.Thunderstore
          path: compiled_release/${{ github.repository_owner }}-${{ env.PACKAGE_NAME }}-${{ inputs.VERSION }}.zip