on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      SKIP_DEBUG:
        required: true
        type: boolean

jobs:
  compile_linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Debug for linux-x64
        if: inputs.SKIP_DEBUG != true
        run: dotnet build --no-restore -c Debug -p:Platform="x64" -p:Version="${{ inputs.VERSION }}"

      - name: Upload Debug for linux-x64
        if: inputs.SKIP_DEBUG != true
        uses: actions/upload-artifact@v5
        with:
          name: MelonLoader.Linux.x64.CI.Debug
          path: Output/Debug/linux-x64

      - name: Build Release for linux-x64
        run: dotnet build --no-restore -c Release -p:Platform="x64" -p:Version="${{ inputs.VERSION }}"

      - name: Upload Release for linux-x64
        uses: actions/upload-artifact@v5
        with:
          name: MelonLoader.Linux.x64.CI.Release
          path: Output/Release/linux-x64